apiVersion: v1
kind: Pod
metadata:
  name: liveness-exec
  labels:
    test: liveness
spec:
  containers:
    - name: liveness
      image: k8s.gcr.io/busybox
      resources:
        limits:
          memory: "64Mi"
          cpu: "50m"
      args: 
        - /bin/sh
        - -c
        - touch /tmp/healty; sleep 30; rm -rf /tmp/healty; sleep 600
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healty
        initialDelaySeconds: 5
        periodSeconds: 5

# Source: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/