apiVersion: apps/v1
kind: Deployment
metadata:
  name: ps-node-app
spec:
  replicas: 3
  minReadySeconds: 10
  selector:
    matchLabels:
      app: ps-node-app
  template:
    metadata:
      labels:
        app: ps-node-app
    spec:
      containers:
        - name: ps-node-app
          image: ps-node-app:3.0
          resources: