apiVersion: v1
kind: Pod
metadata:
  name: docker-volume
spec:
  containers:
    - name: docker
      image: docker
      command: [ "sleep" ]
      args: [ "100000" ]
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-socket
      resources:
  volumes:
    - name: docker-socket
      hostPath:
          path: /var/run/docker.sock
          type: Socket