apiVersion: v1
kind: Pod
metadata:
  name: nginx-alpine-volume
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html
          readOnly: true
      resources:
    - name: html-updater
      image: alpine
      command: [ "/bin/sh", "-c" ]
      args:
        - while true; do date >> /html/index.html; sleep 10; done
      volumeMounts:
        - mountPath: /html
          name: html
      resources:
  volumes:
    - name: html
      emptyDir: {}