apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-secrets-env
  labels:
    app: mongo-secrets-env
data:
  MONGODB_DBNAME: dockerDesktopMongo
  MONGO_INITDB_ROOT_USERNAME: admin

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec: 
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  # StorageClass has a reclaim policy default so it'll be "inherited" by the PV
  # persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /c/temp/data/db
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - docker-desktop

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: mongo
spec: 
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  serviceName: mongo
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      volumes:
        - name: mongo-volume
          persistentVolumeClaim:
            claimName: mongo-pvc
        - name: secrets
          secret:
            secretName: db-passwords
      containers:
        - env:
            - name: MONGODB_DBNAME
              valueFrom:
                  configMapKeyRef:
                    key: MONGODB_DBNAME
                    name: mongo-secrets-env
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: MONGO_INITDB_ROOT_USERNAME
                  name: mongo-secrets-env
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db-password
                  name: db-passwords
          name: mongo
          image: mongo
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - name: mongo-volume
              mountPath: /data/db
            - name: secrets
              mountPath: /etc/db-passwords
              readOnly: true